### ISSUE TITLE
Document exit code usage

### ISSUE THREAD

**Issue by huntc** [typesafehub/conductr-doc#249]
Document that process that fail should always exit with a non-zero exit code. The POSIX convention is to use exit code 1.

Exiting with a 0 will cause ConductR to view the exit as normal and therefore do nothing in terms of restarting it elsewhere.

It may also be helpful to provide some code around our Akka SBR downing of a self member should behave.

**Comment by longmuir** [comment]
I'd like to take this on - mostly to learn about how to contribute to ConductR (and eventually other products) documentation, but also because I ran into this issue.

Looking at the current ConductR docs, would this make sense to add as a second session to the section "Signalling Application State" and a reference to the Split Brain Resolver documentation: http://doc.akka.io/docs/akka/rp-15v01p05/scala/split-brain-resolver.html#Strategies?
